Support carthage
EyreFree/EFColorPicker pull request #24
Opened 2019-11-12 10:33 UTC by ningkexin

2020-04-21 17:07 UTC, EyreFree requested changes

2020-04-21 17:07 UTC, EyreFree commented on README.md
> +You can use [Carthage](https://github.com/Carthage/Carthage) to install SwiftyBeaver by adding that to your Cartfile:
Emmmmn, `SwiftyBeaver`?

2020-05-06 02:41 UTC, ningkexin commented on README.md
> +You can use [Carthage](https://github.com/Carthage/Carthage) to install SwiftyBeaver by adding that to your Cartfile:
Sorry, it has been corrected

2021-03-22 03:55 UTC, EyreFree approved these changes

2021-03-22 03:56 UTC, merged